introduce oneAPI toolkits 2022.1.1

diff --git a/images/docker/iotkit/Dockerfile.ubuntu-18.04 b/images/docker/iotkit/Dockerfile.ubuntu-18.04
--- a/images/docker/iotkit/Dockerfile.ubuntu-18.04
+++ b/images/docker/iotkit/Dockerfile.ubuntu-18.04
@@ -1,118 +1,102 @@
-# Copyright (c) 2019-2020 Intel Corporation.
+# Copyright (c) 2020-2021 Intel Corporation.
 # SPDX-License-Identifier: BSD-3-Clause
-
-# requires oneapi-basekit image, assumes oneapi apt repo is configured
 FROM ubuntu:18.04 as build
 
 RUN mkdir -p /opt/build && mkdir -p /opt/dist
-
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    ca-certificates curl
+    ca-certificates curl && \
+  rm -rf /var/lib/apt/lists/*
 
 # install cmake
 RUN cd /opt/build && \
-    curl -LO https://github.com/Kitware/CMake/releases/download/v3.20.2/cmake-3.20.2-linux-x86_64.sh && \
+    curl -LO https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.sh && \
     mkdir -p /opt/dist//usr/local && \
-    /bin/bash cmake-3.20.2-linux-x86_64.sh --prefix=/opt/dist//usr/local --skip-license
+    /bin/bash cmake-3.22.1-linux-x86_64.sh --prefix=/opt/dist//usr/local --skip-license
+
+
+
+
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
 FROM ubuntu:18.04
+COPY third-party-programs.txt /
+RUN apt-get update && \
+  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+    curl ca-certificates gpg-agent software-properties-common && \
+  rm -rf /var/lib/apt/lists/*
+# repository to install Intel(R) oneAPI Libraries
+RUN curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB | apt-key add -
+RUN echo "deb [trusted=yes] https://apt.repos.intel.com/oneapi all main " > /etc/apt/sources.list.d/oneAPI.list
+
+RUN apt-get update && \
+  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+    curl ca-certificates gpg-agent software-properties-common && \
+  rm -rf /var/lib/apt/lists/*
+# repository to install Intel(R) GPU drivers
+RUN curl -fsSL https://repositories.intel.com/graphics/intel-graphics.key | apt-key add -
+RUN echo "deb [trusted=yes arch=amd64] https://repositories.intel.com/graphics/ubuntu bionic main" > /etc/apt/sources.list.d/intel-graphics.list
+
+RUN apt-get update && \
+  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+    ca-certificates build-essential pkg-config gnupg libarchive13 intel-basekit-getting-started intel-oneapi-advisor intel-oneapi-ccl-devel intel-oneapi-common-licensing intel-oneapi-common-vars intel-oneapi-compiler-dpcpp-cpp intel-oneapi-dal-devel intel-oneapi-dev-utilities intel-oneapi-dnnl-devel intel-oneapi-dpcpp-debugger intel-oneapi-ipp-devel intel-oneapi-ippcp-devel intel-oneapi-libdpstd-devel intel-oneapi-mkl-devel intel-oneapi-onevpl-devel intel-oneapi-python intel-oneapi-tbb-devel intel-oneapi-vtune intel-opencl intel-level-zero-gpu level-zero level-zero-devel intel-iotkit-getting-started intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-inspector  && \
+  rm -rf /var/lib/apt/lists/*
 
 COPY --from=build /opt/dist /
 
-ARG DEBIAN_FRONTEND=noninteractive
-ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
+ENV LANG=C.UTF-8
 
-# install OS tools
-RUN apt-get update -y && \
-apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 \
-build-essential \
-pkg-config \
-ca-certificates \
-gnupg \
-libarchive13 \
-wget
-
-# add apt repo public key
-ARG url=https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
-RUN wget $url
-RUN file=$(basename "$url") && \
-    apt-key add "$file" && \
-    rm "$file"
-
-# configure the repository
-ARG repo=https://apt.repos.intel.com/oneapi
-RUN echo "deb $repo all main" > /etc/apt/sources.list.d/oneAPI.list
-
-# disable cert check
-ARG disable_cert_check=
-RUN if [ "$disable_cert_check" ] ; then echo "Acquire::https::Verify-Peer \"false\";\nAcquire::https::Verify-Host \"false\";" > /etc/apt/apt.conf.d/99-disable-cert-check ; fi
-
-COPY third-party-programs.txt /
-
-# install Intel(R) oneAPI Base Toolkit
-RUN update-ca-certificates --fresh && \
-apt-get update -y && \
-apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 \
-intel-basekit-getting-started \
-intel-oneapi-advisor \
-intel-oneapi-ccl-devel \
-intel-oneapi-common-licensing \
-intel-oneapi-common-vars \
-intel-oneapi-compiler-dpcpp-cpp \
-intel-oneapi-dal-devel \
-intel-oneapi-dev-utilities \
-intel-oneapi-dnnl-devel \
-intel-oneapi-dpcpp-debugger \
-intel-oneapi-ipp-devel \
-intel-oneapi-ippcp-devel \
-intel-oneapi-libdpstd-devel \
-intel-oneapi-mkl-devel \
-intel-oneapi-onevpl-devel \
-intel-oneapi-python \
-intel-oneapi-tbb-devel \
-intel-oneapi-vtune \
---
-
-# install Intel GPU drivers
-RUN echo 'deb [trusted=yes arch=amd64] https://repositories.intel.com/graphics/ubuntu bionic main' \
-> /etc/apt/sources.list.d/intel-graphics.list
-
-ARG url=https://repositories.intel.com/graphics/intel-graphics.key
-RUN wget $url && file=$(basename "$url") && \
-    apt-key add "$file" && \
-    rm "$file"
-
-RUN apt-get update -y && \
-apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 \
-intel-opencl \
-intel-level-zero-gpu \
-level-zero \
-level-zero-devel
-
-# install Intel(R) oneAPI IoT Toolkit
-RUN apt-get update -y && \
-apt-get install -y --no-install-recommends -o=Dpkg::Use-Pty=0 \
-intel-iotkit-getting-started \
-intel-oneapi-common-licensing \
-intel-oneapi-common-vars \
-intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic \
-intel-oneapi-dev-utilities \
-intel-oneapi-inspector \
-intel-oneapi-iot-eclipse-plugins \
---
-
-# setvars.sh environment variables
-RUN env > default_env_vars; \
-. /opt/intel/oneapi/setvars.sh; \
-env > env_vars; \
-diff default_env_vars env_vars \
-| grep ">" | sed  s/..// \
-| sort \
-| sed 's/^/export /' | sed "s/=/='/" | sed "s/$/'/" \
->> /root/.oneapi_env_vars; \
-# clean up
-rm *env_vars; \
-rm -rf /var/lib/apt/lists/*
-
-ENTRYPOINT ["bash", "-c", "source /root/.oneapi_env_vars && \"$@\"", "bash"]
+ENV ACL_BOARD_VENDOR_PATH='/opt/Intel/OpenCLFPGA/oneAPI/Boards'
+ENV ADVISOR_2022_DIR='/opt/intel/oneapi/advisor/2022.0.0'
+ENV APM='/opt/intel/oneapi/advisor/2022.0.0/perfmodels'
+ENV CCL_CONFIGURATION='cpu_gpu_dpcpp'
+ENV CCL_ROOT='/opt/intel/oneapi/ccl/2021.5.0'
+ENV CLASSPATH='/opt/intel/oneapi/mpi/2021.5.0//lib/mpi.jar:/opt/intel/oneapi/dal/2021.5.1/lib/onedal.jar'
+ENV CMAKE_PREFIX_PATH='/opt/intel/oneapi/vpl/2022.0.0:/opt/intel/oneapi/tbb/2021.5.0/env/..:/opt/intel/oneapi/dal/2021.5.1:/opt/intel/oneapi/compiler/2022.0.1/linux/IntelDPCPP'
+ENV CMPLR_ROOT='/opt/intel/oneapi/compiler/2022.0.1'
+ENV CONDA_DEFAULT_ENV='intelpython-python3.9'
+ENV CONDA_EXE='/opt/intel/oneapi/intelpython/latest/bin/conda'
+ENV CONDA_PREFIX='/opt/intel/oneapi/intelpython/latest'
+ENV CONDA_PROMPT_MODIFIER='(intelpython-python3.9) '
+ENV CONDA_PYTHON_EXE='/opt/intel/oneapi/intelpython/latest/bin/python'
+ENV CONDA_SHLVL='1'
+ENV CPATH='/opt/intel/oneapi/vpl/2022.0.0/include:/opt/intel/oneapi/tbb/2021.5.0/env/../include:/opt/intel/oneapi/mpi/2021.5.0//include:/opt/intel/oneapi/mkl/2022.0.1/include:/opt/intel/oneapi/ippcp/2021.5.0/include:/opt/intel/oneapi/ipp/2021.5.1/include:/opt/intel/oneapi/dpl/2021.6.0/linux/include:/opt/intel/oneapi/dnnl/2022.0.1/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/dev-utilities/2021.5.1/include:/opt/intel/oneapi/dal/2021.5.1/include:/opt/intel/oneapi/ccl/2021.5.0/include/cpu_gpu_dpcpp'
+ENV DAALROOT='/opt/intel/oneapi/dal/2021.5.1'
+ENV DALROOT='/opt/intel/oneapi/dal/2021.5.1'
+ENV DAL_MAJOR_BINARY='1'
+ENV DAL_MINOR_BINARY='1'
+ENV DNNLROOT='/opt/intel/oneapi/dnnl/2022.0.1/cpu_dpcpp_gpu_dpcpp'
+ENV DPL_ROOT='/opt/intel/oneapi/dpl/2021.6.0'
+ENV FI_PROVIDER_PATH='/opt/intel/oneapi/mpi/2021.5.0//libfabric/lib/prov:/usr/lib64/libfabric'
+ENV FPGA_VARS_ARGS=''
+ENV FPGA_VARS_DIR='/opt/intel/oneapi/compiler/2022.0.1/linux/lib/oclfpga'
+ENV GDB_INFO='/opt/intel/oneapi/debugger/2021.5.0/documentation/info/'
+ENV INFOPATH='/opt/intel/oneapi/debugger/2021.5.0/gdb/intel64/lib'
+ENV INSPECTOR_2022_DIR='/opt/intel/oneapi/inspector/2022.0.0'
+ENV INTELFPGAOCLSDKROOT='/opt/intel/oneapi/compiler/2022.0.1/linux/lib/oclfpga'
+ENV INTEL_PYTHONHOME='/opt/intel/oneapi/debugger/2021.5.0/dep'
+ENV IPPCP_TARGET_ARCH='intel64'
+ENV IPPCRYPTOROOT='/opt/intel/oneapi/ippcp/2021.5.0'
+ENV IPPROOT='/opt/intel/oneapi/ipp/2021.5.1'
+ENV IPP_TARGET_ARCH='intel64'
+ENV I_MPI_ROOT='/opt/intel/oneapi/mpi/2021.5.0'
+ENV LD_LIBRARY_PATH='/opt/intel/oneapi/vpl/2022.0.0/lib:/opt/intel/oneapi/tbb/2021.5.0/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.5.0//libfabric/lib:/opt/intel/oneapi/mpi/2021.5.0//lib/release:/opt/intel/oneapi/mpi/2021.5.0//lib:/opt/intel/oneapi/mkl/2022.0.1/lib/intel64:/opt/intel/oneapi/ippcp/2021.5.0/lib/intel64:/opt/intel/oneapi/ipp/2021.5.1/lib/intel64:/opt/intel/oneapi/dnnl/2022.0.1/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/debugger/2021.5.0/gdb/intel64/lib:/opt/intel/oneapi/debugger/2021.5.0/libipt/intel64/lib:/opt/intel/oneapi/debugger/2021.5.0/dep/lib:/opt/intel/oneapi/dal/2021.5.1/lib/intel64:/opt/intel/oneapi/compiler/2022.0.1/linux/lib:/opt/intel/oneapi/compiler/2022.0.1/linux/lib/x64:/opt/intel/oneapi/compiler/2022.0.1/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2022.0.1/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/ccl/2021.5.0/lib/cpu_gpu_dpcpp'
+ENV LIBRARY_PATH='/opt/intel/oneapi/vpl/2022.0.0/lib:/opt/intel/oneapi/tbb/2021.5.0/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.5.0//libfabric/lib:/opt/intel/oneapi/mpi/2021.5.0//lib/release:/opt/intel/oneapi/mpi/2021.5.0//lib:/opt/intel/oneapi/mkl/2022.0.1/lib/intel64:/opt/intel/oneapi/ippcp/2021.5.0/lib/intel64:/opt/intel/oneapi/ipp/2021.5.1/lib/intel64:/opt/intel/oneapi/dnnl/2022.0.1/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/dal/2021.5.1/lib/intel64:/opt/intel/oneapi/compiler/2022.0.1/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/compiler/2022.0.1/linux/lib:/opt/intel/oneapi/ccl/2021.5.0/lib/cpu_gpu_dpcpp'
+ENV MANPATH='/opt/intel/oneapi/mpi/2021.5.0/man:/opt/intel/oneapi/debugger/2021.5.0/documentation/man:/opt/intel/oneapi/compiler/2022.0.1/documentation/en/man/common::'
+ENV MKLROOT='/opt/intel/oneapi/mkl/2022.0.1'
+ENV NLSPATH='/opt/intel/oneapi/mkl/2022.0.1/lib/intel64/locale/%l_%t/%N:/opt/intel/oneapi/compiler/2022.0.1/linux/compiler/lib/intel64_lin/locale/%l_%t/%N'
+ENV OCL_ICD_FILENAMES='libintelocl_emu.so:libalteracl.so:/opt/intel/oneapi/compiler/2022.0.1/linux/lib/x64/libintelocl.so'
+ENV ONEAPI_ROOT='/opt/intel/oneapi'
+ENV PATH='/opt/intel/oneapi/vtune/2022.0.0/bin64:/opt/intel/oneapi/vpl/2022.0.0/bin:/opt/intel/oneapi/mpi/2021.5.0//libfabric/bin:/opt/intel/oneapi/mpi/2021.5.0//bin:/opt/intel/oneapi/mkl/2022.0.1/bin/intel64:/opt/intel/oneapi/intelpython/latest/bin:/opt/intel/oneapi/intelpython/latest/condabin:/opt/intel/oneapi/inspector/2022.0.0/bin64:/opt/intel/oneapi/dev-utilities/2021.5.1/bin:/opt/intel/oneapi/debugger/2021.5.0/gdb/intel64/bin:/opt/intel/oneapi/compiler/2022.0.1/linux/lib/oclfpga/bin:/opt/intel/oneapi/compiler/2022.0.1/linux/bin/intel64:/opt/intel/oneapi/compiler/2022.0.1/linux/bin:/opt/intel/oneapi/advisor/2022.0.0/bin64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+ENV PKG_CONFIG_PATH='/opt/intel/oneapi/vtune/2022.0.0/include/pkgconfig/lib64:/opt/intel/oneapi/vpl/2022.0.0/lib/pkgconfig:/opt/intel/oneapi/tbb/2021.5.0/env/../lib/pkgconfig:/opt/intel/oneapi/mpi/2021.5.0/lib/pkgconfig:/opt/intel/oneapi/mkl/2022.0.1/lib/pkgconfig:/opt/intel/oneapi/ippcp/2021.5.0/lib/pkgconfig:/opt/intel/oneapi/inspector/2022.0.0/include/pkgconfig/lib64:/opt/intel/oneapi/dpl/2021.6.0/lib/pkgconfig:/opt/intel/oneapi/dnnl/2022.0.1/cpu_dpcpp_gpu_dpcpp/../lib/pkgconfig:/opt/intel/oneapi/dal/2021.5.1/lib/pkgconfig:/opt/intel/oneapi/compiler/2022.0.1/lib/pkgconfig:/opt/intel/oneapi/ccl/2021.5.0/lib/pkgconfig:/opt/intel/oneapi/advisor/2022.0.0/include/pkgconfig/lib64:'
+ENV PYTHONPATH='/opt/intel/oneapi/advisor/2022.0.0/pythonapi'
+ENV SETVARS_COMPLETED='1'
+ENV TBBROOT='/opt/intel/oneapi/tbb/2021.5.0/env/..'
+ENV VTUNE_PROFILER_2022_DIR='/opt/intel/oneapi/vtune/2022.0.0'
+ENV _CE_CONDA=''
+ENV _CE_M=''
